CREATE DATABASE IF NOT EXISTS grafana;
CREATE DATABASE IF NOT EXISTS keycloak;

GRANT ALL PRIVILEGES ON *.* TO 'root'@localhost IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON *.* TO 'grafana'@localhost IDENTIFIED BY 'grafana' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'grafana'@'%' IDENTIFIED BY 'grafana' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON *.* TO 'keycloak'@localhost IDENTIFIED BY 'keycloak' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'keycloak'@'%' IDENTIFIED BY 'keycloak' WITH GRANT OPTION;


FLUSH PRIVILEGES;
 